/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PropFirmRouteImport } from './routes/prop-firm'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LiveTradingRouteImport } from './routes/live-trading'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlphaPortfolioRouteImport } from './routes/alpha-portfolio'
import { Route as AlphaFactoryRouteImport } from './routes/alpha-factory'
import { Route as AiCenterRouteImport } from './routes/ai-center'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmRoute = PropFirmRouteImport.update({
  id: '/prop-firm',
  path: '/prop-firm',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTradingRoute = LiveTradingRouteImport.update({
  id: '/live-trading',
  path: '/live-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaPortfolioRoute = AlphaPortfolioRouteImport.update({
  id: '/alpha-portfolio',
  path: '/alpha-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaFactoryRoute = AlphaFactoryRouteImport.update({
  id: '/alpha-factory',
  path: '/alpha-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCenterRoute = AiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-center': typeof AiCenterRoute
  '/alpha-factory': typeof AlphaFactoryRoute
  '/alpha-portfolio': typeof AlphaPortfolioRoute
  '/auth': typeof AuthRoute
  '/backtesting': typeof BacktestingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institutional': typeof InstitutionalRoute
  '/investor': typeof InvestorRoute
  '/live-trading': typeof LiveTradingRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/performance': typeof PerformanceRoute
  '/portfolio': typeof PortfolioRoute
  '/prop-firm': typeof PropFirmRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-center': typeof AiCenterRoute
  '/alpha-factory': typeof AlphaFactoryRoute
  '/alpha-portfolio': typeof AlphaPortfolioRoute
  '/auth': typeof AuthRoute
  '/backtesting': typeof BacktestingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institutional': typeof InstitutionalRoute
  '/investor': typeof InvestorRoute
  '/live-trading': typeof LiveTradingRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/performance': typeof PerformanceRoute
  '/portfolio': typeof PortfolioRoute
  '/prop-firm': typeof PropFirmRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-center': typeof AiCenterRoute
  '/alpha-factory': typeof AlphaFactoryRoute
  '/alpha-portfolio': typeof AlphaPortfolioRoute
  '/auth': typeof AuthRoute
  '/backtesting': typeof BacktestingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/dashboard': typeof DashboardRoute
  '/infrastructure': typeof InfrastructureRoute
  '/institutional': typeof InstitutionalRoute
  '/investor': typeof InvestorRoute
  '/live-trading': typeof LiveTradingRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/performance': typeof PerformanceRoute
  '/portfolio': typeof PortfolioRoute
  '/prop-firm': typeof PropFirmRoute
  '/research': typeof ResearchRoute
  '/risk': typeof RiskRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-center'
    | '/alpha-factory'
    | '/alpha-portfolio'
    | '/auth'
    | '/backtesting'
    | '/consultation'
    | '/contact'
    | '/copy-trading'
    | '/dashboard'
    | '/infrastructure'
    | '/institutional'
    | '/investor'
    | '/live-trading'
    | '/marketplace'
    | '/payment-callback'
    | '/performance'
    | '/portfolio'
    | '/prop-firm'
    | '/research'
    | '/risk'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-center'
    | '/alpha-factory'
    | '/alpha-portfolio'
    | '/auth'
    | '/backtesting'
    | '/consultation'
    | '/contact'
    | '/copy-trading'
    | '/dashboard'
    | '/infrastructure'
    | '/institutional'
    | '/investor'
    | '/live-trading'
    | '/marketplace'
    | '/payment-callback'
    | '/performance'
    | '/portfolio'
    | '/prop-firm'
    | '/research'
    | '/risk'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/ai-center'
    | '/alpha-factory'
    | '/alpha-portfolio'
    | '/auth'
    | '/backtesting'
    | '/consultation'
    | '/contact'
    | '/copy-trading'
    | '/dashboard'
    | '/infrastructure'
    | '/institutional'
    | '/investor'
    | '/live-trading'
    | '/marketplace'
    | '/payment-callback'
    | '/performance'
    | '/portfolio'
    | '/prop-firm'
    | '/research'
    | '/risk'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AiCenterRoute: typeof AiCenterRoute
  AlphaFactoryRoute: typeof AlphaFactoryRoute
  AlphaPortfolioRoute: typeof AlphaPortfolioRoute
  AuthRoute: typeof AuthRoute
  BacktestingRoute: typeof BacktestingRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  CopyTradingRoute: typeof CopyTradingRoute
  DashboardRoute: typeof DashboardRoute
  InfrastructureRoute: typeof InfrastructureRoute
  InstitutionalRoute: typeof InstitutionalRoute
  InvestorRoute: typeof InvestorRoute
  LiveTradingRoute: typeof LiveTradingRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PerformanceRoute: typeof PerformanceRoute
  PortfolioRoute: typeof PortfolioRoute
  PropFirmRoute: typeof PropFirmRoute
  ResearchRoute: typeof ResearchRoute
  RiskRoute: typeof RiskRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firm': {
      id: '/prop-firm'
      path: '/prop-firm'
      fullPath: '/prop-firm'
      preLoaderRoute: typeof PropFirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trading': {
      id: '/live-trading'
      path: '/live-trading'
      fullPath: '/live-trading'
      preLoaderRoute: typeof LiveTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-portfolio': {
      id: '/alpha-portfolio'
      path: '/alpha-portfolio'
      fullPath: '/alpha-portfolio'
      preLoaderRoute: typeof AlphaPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-factory': {
      id: '/alpha-factory'
      path: '/alpha-factory'
      fullPath: '/alpha-factory'
      preLoaderRoute: typeof AlphaFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-center': {
      id: '/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AiCenterRoute: AiCenterRoute,
  AlphaFactoryRoute: AlphaFactoryRoute,
  AlphaPortfolioRoute: AlphaPortfolioRoute,
  AuthRoute: AuthRoute,
  BacktestingRoute: BacktestingRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  CopyTradingRoute: CopyTradingRoute,
  DashboardRoute: DashboardRoute,
  InfrastructureRoute: InfrastructureRoute,
  InstitutionalRoute: InstitutionalRoute,
  InvestorRoute: InvestorRoute,
  LiveTradingRoute: LiveTradingRoute,
  MarketplaceRoute: MarketplaceRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PerformanceRoute: PerformanceRoute,
  PortfolioRoute: PortfolioRoute,
  PropFirmRoute: PropFirmRoute,
  ResearchRoute: ResearchRoute,
  RiskRoute: RiskRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
